name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NODE_ENV: production
  DATABASE_URI: mongodb://mongo:jacfweio@localhost:27017
  DATABASE_NAME: database-ci
  JWT_SECRET: supersecret

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Spawn database
        run: docker run -d -p 27017:27017 --name database-ci -e MONGO_INITDB=database-ci -e MONGO_INITDB_ROOT_USERNAME=mongo -e MONGO_INITDB_ROOT_PASSWORD=jacfweio mongo

      - name: Install client deps
        working-directory: client
        run: npm install

      - name: Install server deps
        working-directory: server
        run: npm install

      - name: Start server in the background
        working-directory: server
        run: npm run start &

      - name: Start client in the background
        working-directory: client
        run: npm run dev &

      - name: Cypress
        working-directory: client
        run: npx cypress run

      - name: Save screenshots
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: client/cypress/screenshots

      - name: Save videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: client/cypress/videos

      - name: clear database
        run: docker stop database-ci

      - name: delete database
        run: docker rm database-ci
